# Question 1

In [2]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2

In [11]:
import numpy as np
list1=[90,12,3,24,5]
list2=[132,22,30,13,55]
ary1=np.array(list1)
ary2=np.array(list2)
ary3=np.concatenate((ary1,ary2), axis=0, out=None)
print(np.sort(ary3))

[  3   5  12  13  22  24  30  55  90 132]


# Question 3

In [12]:
import numpy as np
arr = np.array( [[ 13, 21, 93],
                 [ 42, 62, 51]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Size of array:  6


# Questions 4

In [18]:
import numpy as np
ary = np.array([ 13, 21, 93])
print(ary.shape)
ary2 = ary[:,np.newaxis]
print(ary2)
print(ary2.shape)

(3,)
[[13]
 [21]
 [93]]
(3, 1)


# Question 5

In [23]:
import numpy as np 
  
a = np.array([[112, 22], 
              [31, 14]]) 
b = np.array([[51, 66], 
              [71, 18]]) 
# vertical stack 
print("Vertical stack:\n", np.vstack((a, b))) 
  
# horizontal stack
print("\nHorizontal stack:\n", np.hstack((a, b))) 

Vertical stack:
 [[112  22]
 [ 31  14]
 [ 51  66]
 [ 71  18]]

Horizontal stack:
 [[112  22  51  66]
 [ 31  14  71  18]]


# Question 6

In [31]:
import numpy as np 
list1 = np.array([1, 1, 2, 3, 4, 4, 1])
(unique, counts) = np.unique(list1, return_counts=True)
print("array of unique numbers is:",unique,"and count of each element is: ", counts,"respectively")

array of unique numbers is: [1 2 3 4] and count of each element is:  [3 1 1 2] respectively
